/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RezervaceRouteImport } from './routes/rezervace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnBookingRouteImport } from './routes/en.booking'
import { Route as ApiSouborFileKeyRouteImport } from './routes/api/soubor.$fileKey'

const RezervaceRoute = RezervaceRouteImport.update({
  id: '/rezervace',
  path: '/rezervace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBookingRoute = EnBookingRouteImport.update({
  id: '/en/booking',
  path: '/en/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSouborFileKeyRoute = ApiSouborFileKeyRouteImport.update({
  id: '/api/soubor/$fileKey',
  path: '/api/soubor/$fileKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rezervace': typeof RezervaceRoute
  '/en/booking': typeof EnBookingRoute
  '/en/': typeof EnIndexRoute
  '/api/soubor/$fileKey': typeof ApiSouborFileKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rezervace': typeof RezervaceRoute
  '/en/booking': typeof EnBookingRoute
  '/en': typeof EnIndexRoute
  '/api/soubor/$fileKey': typeof ApiSouborFileKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rezervace': typeof RezervaceRoute
  '/en/booking': typeof EnBookingRoute
  '/en/': typeof EnIndexRoute
  '/api/soubor/$fileKey': typeof ApiSouborFileKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rezervace'
    | '/en/booking'
    | '/en/'
    | '/api/soubor/$fileKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/rezervace'
    | '/en/booking'
    | '/en'
    | '/api/soubor/$fileKey'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/rezervace'
    | '/en/booking'
    | '/en/'
    | '/api/soubor/$fileKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  RezervaceRoute: typeof RezervaceRoute
  EnBookingRoute: typeof EnBookingRoute
  EnIndexRoute: typeof EnIndexRoute
  ApiSouborFileKeyRoute: typeof ApiSouborFileKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rezervace': {
      id: '/rezervace'
      path: '/rezervace'
      fullPath: '/rezervace'
      preLoaderRoute: typeof RezervaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/booking': {
      id: '/en/booking'
      path: '/en/booking'
      fullPath: '/en/booking'
      preLoaderRoute: typeof EnBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soubor/$fileKey': {
      id: '/api/soubor/$fileKey'
      path: '/api/soubor/$fileKey'
      fullPath: '/api/soubor/$fileKey'
      preLoaderRoute: typeof ApiSouborFileKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  RezervaceRoute: RezervaceRoute,
  EnBookingRoute: EnBookingRoute,
  EnIndexRoute: EnIndexRoute,
  ApiSouborFileKeyRoute: ApiSouborFileKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
