/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RezervaceRouteImport } from './routes/rezervace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SouborFileKeyRouteImport } from './routes/soubor.$fileKey'

const RezervaceRoute = RezervaceRouteImport.update({
  id: '/rezervace',
  path: '/rezervace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SouborFileKeyRoute = SouborFileKeyRouteImport.update({
  id: '/soubor/$fileKey',
  path: '/soubor/$fileKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rezervace': typeof RezervaceRoute
  '/soubor/$fileKey': typeof SouborFileKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rezervace': typeof RezervaceRoute
  '/soubor/$fileKey': typeof SouborFileKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rezervace': typeof RezervaceRoute
  '/soubor/$fileKey': typeof SouborFileKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/rezervace' | '/soubor/$fileKey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/rezervace' | '/soubor/$fileKey'
  id: '__root__' | '/' | '/auth' | '/rezervace' | '/soubor/$fileKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  RezervaceRoute: typeof RezervaceRoute
  SouborFileKeyRoute: typeof SouborFileKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rezervace': {
      id: '/rezervace'
      path: '/rezervace'
      fullPath: '/rezervace'
      preLoaderRoute: typeof RezervaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soubor/$fileKey': {
      id: '/soubor/$fileKey'
      path: '/soubor/$fileKey'
      fullPath: '/soubor/$fileKey'
      preLoaderRoute: typeof SouborFileKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  RezervaceRoute: RezervaceRoute,
  SouborFileKeyRoute: SouborFileKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
